/**
 * Stage 1: Ingest
 * 
 * Normalizes the incoming request into canonical format.
 * Validates request structure and action types against scenario.
 * 
 * @version 1.0.0
 */

import type { Stage, StageContext, StageResult, IngestArtifacts } from '../core/stage-interface.js';
import type { DecisionEnvelope } from '../core/decision-envelope.js';
import type { Action } from '../core/types.js';
import { InvalidRequestError, InvalidActionTypeError } from '../core/errors.js';

export class IngestStage implements Stage<IngestArtifacts> {
  readonly stageNumber = 1;
  readonly stageName = 'ingest';
  
  async execute(
    envelope: DecisionEnvelope,
    context: StageContext
  ): Promise<StageResult<IngestArtifacts>> {
    const startTime = performance.now();
    
    // CRITICAL: Generate decision_id inside pipeline, never from client
    // This is non-negotiable for audit integrity
    if (!envelope.decision_id) {
      throw new Error('Decision ID must be generated by createEnvelope, not passed from client');
    }
    
    // Validate request has required fields
    this.validateRequest(envelope);
    
    // Validate actions against scenario action types
    const normalizedActions = this.normalizeActions(
      envelope.normalized_actions,
      context.scenario
    );
    
    // Update envelope with normalized actions
    const updatedEnvelope: DecisionEnvelope = {
      ...envelope,
      normalized_actions: normalizedActions,
    };
    
    const artifacts: IngestArtifacts = {
      normalized_request: true,
      action_count: normalizedActions.length,
      signal_count: Object.keys(envelope.request.signals).length,
    };
    
    return {
      envelope: updatedEnvelope,
      artifacts,
      duration_ms: performance.now() - startTime,
    };
  }
  
  private validateRequest(envelope: DecisionEnvelope): void {
    const { request } = envelope;
    
    if (!request.scenario_id) {
      throw new InvalidRequestError('Missing scenario_id');
    }
    
    if (!request.user_id) {
      throw new InvalidRequestError('Missing user_id');
    }
    
    if (!request.actions || request.actions.length === 0) {
      throw new InvalidRequestError('No actions provided');
    }
    
    if (!request.context?.current_time) {
      throw new InvalidRequestError('Missing context.current_time');
    }
  }
  
  private normalizeActions(
    actions: Action[],
    scenario: { actions: { action_types: Array<{ type_id: string }> } }
  ): Action[] {
    const validTypeIds = new Set(
      scenario.actions.action_types.map(t => t.type_id)
    );
    
    const normalized: Action[] = [];
    
    for (const action of actions) {
      if (!action.action_id) {
        throw new InvalidRequestError('Action missing action_id');
      }
      
      if (!action.type_id) {
        throw new InvalidRequestError(`Action ${action.action_id} missing type_id`);
      }
      
      if (!validTypeIds.has(action.type_id)) {
        throw new InvalidActionTypeError(
          `Invalid action type: ${action.type_id}`,
          { action_id: action.action_id, type_id: action.type_id }
        );
      }
      
      normalized.push({
        action_id: action.action_id,
        type_id: action.type_id,
        attributes: action.attributes ?? {},
      });
    }
    
    return normalized;
  }
}

export function createIngestStage(): IngestStage {
  return new IngestStage();
}
